### ISSUE TITLE
当dom 出现滚动条情况时候，则canvas与dom对应的坐标会不一致，导致标记错位

### ISSUE THREAD

**Issue by ibigtou** [DLillard0/canvas-highlighter#1]
情况说明
当dom 出现滚动条情况时候，则canvas与dom对应的坐标会不一致，导致标记错位
我自己的修改方法
监听dom滚动事件，获取滚动距离，并将canvas的大小设置为dom的实际大小
以此来获取rect的真实坐标位置

**Comment by DLillard0** [comment]
按设计来说文本容器本身应该与 canvas 保持一致大小, 如果需要超出滚动建议再在外面套一个 div 实现, 保证文本容器与 canvas 同时滚动

**Comment by ibigtou** [comment]
> 

已经按照您的建议作出修改，问题已经解决
并且根据您的源码，我转换成了react的版本，使用hooks封装一些操作（getSelection等），使用react-konva进行标记渲染
很受用。
给大佬磕头了

**Comment by DLillard0** [comment]
ok
