### ISSUE TITLE
大佬，我想问下，创建的Canvashighlight实例对象 如何销毁。

### ISSUE THREAD

**Issue by tjt740** [DLillard0/canvas-highlighter#10]
除了.clear 清楚全部的range以外，能不能直接把整个实例对象销毁掉。频繁创建导致内存溢出了。。。

**Comment by tjt740** [comment]
版本是  "canvas-highlighter": "^1.0.4",

**Comment by tjt740** [comment]
![image](https://github.com/DLillard0/canvas-highlighter/assets/59766436/77d5d5d9-6f11-44f0-90cc-dd1f0146355c)
我在频繁创建的原因是因为,每一次 【上一条】【下一条】会改变文案内容，想着重新new一个对象出来构造，但是正式因为new了一个对象。就导致内存溢出了，而且我尝试let xxx = null; xxx = new CanvasHighlighter()的方法，清除实例化对象，也不起作用。 难顶。。。。

**Comment by DLillard0** [comment]
每 new 一个实例都会往 container 下 append 一个 canvas 元素，可以这样去删除当前实例下的 canvas 元素：
```js
const highlighter = new CanvasHighlighter(container)
highlighter.stage.container.remove() // 移除元素
```

**Comment by DLillard0** [comment]
内存溢出应该不是 js 对象导致的，是 dom 上的 canvas 对象导致的，新建时清理上一个实例的 canvas 应该就不会了

**Comment by tjt740** [comment]
请问如何清理实例上的canvas呢
<img width="784" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/19aef479-7b66-4b51-bab0-a4cde9d5660b">
我是这么操作，只能把对象的引用消除。

reset() 中 只有一个与 hightlighter相关的
<img width="753" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/bc8714ed-84c6-4617-bfdb-50a1075e917f">

**Comment by DLillard0** [comment]
这样就可以了
```js
highlighter.stage.container.remove() // 移除元素
```
这样直接整个删除，不需要调 clear

**Comment by tjt740** [comment]
> 这样就可以了
> 
> ```js
> highlighter.stage.container.remove() // 移除元素
> ```
> 
> 这样直接整个删除，不需要调 clear

感谢 我试下 现在

**Comment by tjt740** [comment]
可以的 很好用解决了
