### ISSUE TITLE
需要滑动区域用attachShadow({ mode: "open" })渲染

### ISSUE THREAD

**Issue by qilong1997** [DLillard0/canvas-highlighter#13]
需要滑动区域用attachShadow({ mode: "open" })渲染的内容，highlighter.getSelectionRange()获取不到内容如何解决

**Comment by DLillard0** [comment]
@qilong1997 很可惜，目前 [getSelection](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection) API 没办法支持 ShadowDOM 内部的 selection 选中监听，参考这个 [issue](https://github.com/WICG/webcomponents/issues/79)，目前有在讨论通过一个新的 API [getComposedRange](https://github.com/w3c/selection-api/issues/161) 来支持 ShadowDOM，但目前还没有浏览器实现，所以暂时没办法解决这个问题。
