### ISSUE TITLE
canvas崩溃

### ISSUE THREAD

**Issue by JimboXie** [DLillard0/canvas-highlighter#3]
内容过多时候，canvas就会崩溃，请问如何解决

**Comment by DLillard0** [comment]
是标注内容过多会崩溃吗？

**Comment by JimboXie** [comment]
> 是标注内容过多会崩溃吗？

是富文本内容过多的时候，Konva所渲染的canvas就会崩溃

**Comment by DLillard0** [comment]
> 是富文本内容过多的时候，Konva所渲染的canvas就会崩溃

Konva 渲染的 canvas 应该跟富文本内容没关系的，能不能提供个 demo 看一下

**Comment by JimboXie** [comment]
> > 是富文本内容过多的时候，Konva所渲染的canvas就会崩溃
> 
> Konva 渲染的 canvas 应该跟富文本内容没关系的，能不能提供个 demo 看一下

[yuque.html.zip](https://github.com/DLillard0/canvas-highlighter/files/10172516/yuque.html.zip)

**Comment by DLillard0** [comment]
> 是富文本内容过多的时候，Konva所渲染的canvas就会崩溃

我看了你的提供的 demo，其实是由于 canvas 元素高度太大导致的内存占用超出问题，这个是普通 canvas 元素都有的问题，我在 1.0.2 版本里面添加了像素比（pixelRatio）的配置，你的 demo 我将 canvas 像素比设置为 0.9 就不会崩溃了，虽然还是有一点卡顿，所以我觉得你可以设置得更小，比如 0.7 或者 0.6 这样子，这个值可以根据你实际的 canvas 大小去调整，虽然这会牺牲一些清晰度，但是能比较好的解决内存占用过多的问题。

**Comment by someqq** [comment]
在PC,CHROME浏览器，360浏览器，canvas不能超过16384*16384像素，语雀不知道怎么做的，是多画几个canvas吗，建议可以改进下这里，我一篇文章46836px的高度，看语雀都无压力

**Comment by DLillard0** [comment]
> 在PC,CHROME浏览器，360浏览器，canvas不能超过16384*16384像素，语雀不知道怎么做的，是多画几个canvas吗，建议可以改进下这里，我一篇文章46836px的高度，看语雀都无压力

canvas 占用内存是看面积的，语雀文章 46836 的高度但宽度最多也就 1920 那肯定没问题的

**Comment by JimboXie** [comment]
> > 是富文本内容过多的时候，Konva所渲染的canvas就会崩溃
> 
> 我看了你的提供的 demo，其实是由于 canvas 元素高度太大导致的内存占用超出问题，这个是普通 canvas 元素都有的问题，我在 1.0.2 版本里面添加了像素比（pixelRatio）的配置，你的 demo 我将 canvas 像素比设置为 0.9 就不会崩溃了，虽然还是有一点卡顿，所以我觉得你可以设置得更小，比如 0.7 或者 0.6 这样子，这个值可以根据你实际的 canvas 大小去调整，虽然这会牺牲一些清晰度，但是能比较好的解决内存占用过多的问题。

好的，谢谢大佬

**Comment by JimboXie** [comment]
> 在PC,CHROME浏览器，360浏览器，canvas不能超过16384*16384像素，语雀不知道怎么做的，是多画几个canvas吗，建议可以改进下这里，我一篇文章46836px的高度，看语雀都无压力

受教了，谢谢
