### ISSUE TITLE
是否有根据鼠标点击的坐标获取所有的rangeIds

### ISSUE THREAD

**Issue by rrrrrasie** [DLillard0/canvas-highlighter#4]
现有方法 geRangeIdByPointer 能够通过鼠标点击坐标获取 1 个相应的 rangeId，有没有什么方法可以通过鼠标点击坐标获取所有对应的 rangeId（有个场景是重复划词，点击后需要展示出所有的这个划词的相关评论弹窗）？请教下大佬，有没有什么好的办法~~

**Comment by DLillard0** [comment]
已在 1.0.3 版本新增了 getAllRangeIdByPointer 方法，可以获取点击坐标下的 rangeId 集合。

**Comment by rrrrrasie** [comment]
好的，感谢！
