### ISSUE TITLE
大佬 你好，请问是否可以增加config中自定义或者其他图形呢 

### ISSUE THREAD

**Issue by tjt740** [DLillard0/canvas-highlighter#6]
<img width="843" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/c197f7da-ea2d-4dc6-b4d7-15fad051aaf1">
想增加个其他图形在这两个图形下面  该如何操作呢

**Comment by DLillard0** [comment]
@tjt740 我在 v1.0.4 版本新增了添加自定义图形的功能，请参考[文档](https://github.com/DLillard0/canvas-highlighter#%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E5%BD%A2)。

**Comment by tjt740** [comment]
> 

感谢大佬，我现在研究下
