### ISSUE TITLE
大佬 我看到你1.0.4版本中添加了自定义图形的功能，想问下有没有代码片段能贴出来让我学习下怎么使用呢，实在是学术不精

### ISSUE THREAD

**Issue by tjt740** [DLillard0/canvas-highlighter#7]
如题
<img width="952" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/a55d6d0b-ed0f-4041-a646-45823c1c3bf2">
实在是没搞懂 - -

**Comment by DLillard0** [comment]
@tjt740 不好意思，文档写错了，我更新了，你再看看

**Comment by tjt740** [comment]
<img width="837" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/c94ea301-5524-4f33-a432-19142c260926">
 大佬,我使用1.0.4版本的时候,看到貌似没有扩展shapeConstructor的方法。
 
<img width="743" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/f3f3fa29-ee73-4da3-a10b-19d0349d4b36">

**Comment by DLillard0** [comment]
@tjt740 这看起来你装的还是 1.0.3 的版本，你指定版本安装一下
![image](https://github.com/DLillard0/canvas-highlighter/assets/53611763/61a1a282-0660-4d77-9d64-4557089d4c8f)

**Comment by tjt740** [comment]
我再试一下哈

**Comment by tjt740** [comment]
<img width="586" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/43fa4820-70ed-4595-8d29-8fc17ce922a8">
 是否是因为没发布的原因呢 找不到1.0.4版本

**Comment by DLillard0** [comment]
npm 是查得到得：https://www.npmjs.com/package/canvas-highlighter?activeTab=versions
你看一下是不是你 npm 那个源还没同步

**Comment by tjt740** [comment]
好的 我现在排查一下问题 感谢感谢

**Comment by tjt740** [comment]
昨天的问题已解决，问题是阿里巴巴这边的tnpm 没有同步镜像源所致，感谢大佬。
