### ISSUE TITLE
你好，在换行的情况下，创建矩形方框的时候出现了两个

### ISSUE THREAD

**Issue by tjt740** [DLillard0/canvas-highlighter#8]
如图：
在文本不换行的情况下，创建矩形方框是正常 的。但是如果文本换行了就会出现两个方框，用line线段划词是没有问题的。目前只发现react画框有这种问题
<img width="1301" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/f5ba58f0-0231-4ae5-9d2d-7c13585b260b">
<img width="1133" alt="image" src="https://github.com/DLillard0/canvas-highlighter/assets/59766436/8997b133-a05a-45a1-bd4d-6b935bb6cc44">

**Comment by DLillard0** [comment]
这样看起来也没问题呀，一行放不下就拆分成为两个，预期的效果是怎么样的呢

**Comment by tjt740** [comment]
预期的结果是换行的同时，不新开两个矩形，使用一个矩形 类似 “[xxxx] ” 这种形状。 好实现吗

**Comment by DLillard0** [comment]
@tjt740 我在 1.0.5 版本中增加了调用构造函数时传递的参数，可以参考[文档](https://github.com/DLillard0/canvas-highlighter#%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E5%BD%A2)
可以通过类似以下的方式实现你说的功能：
```javascript
function createLine(position, id, domRects, index) {
  const { x, y, width, height } = position
  let points
  let closed = false
  // 只有一个区域时，直接绘制矩形
  if (domRects.length === 1) {
    points = [
      x,
      y,
      x + width,
      y,
      x + width,
      y + height,
      x,
      y + height
    ]
    closed = true
  // 有多个区域时，第一个区域不绘制右边框线
  } else if (index === 0) {
    points = [
      x + width,
      y,
      x,
      y,
      x,
      y + height,
      x + width,
      y + height
    ]
  // 第二个区域不绘制左边框线
  } else if (index === 1) {
    points = [
      x,
      y,
      x + width,
      y,
      x + width,
      y + height,
      x,
      y + height
    ]
  }
  return new Konva.Line({
    points,
    closed,
    stroke: 'red',
    strokeWidth: 2
  })
}
```

**Comment by tjt740** [comment]
懂了 感谢大佬 明天上班我来试下哈

**Comment by tjt740** [comment]
完美哦
