### ISSUE TITLE
界面滚动了，标记就会出错，怎么处理？

### ISSUE THREAD

**Issue by gaoxin3220119** [DLillard0/canvas-highlighter#9]
如题

**Comment by gaoxin3220119** [comment]
没有认真看代码，上面的已经解决了。

但是怎么才能把标记保存下来，下次打开重新渲染呢？

**Comment by DLillard0** [comment]
可以参考 [demo](https://github.com/DLillard0/canvas-highlighter/blob/main/docs/yuque.html#L157)，只需要保存 range 信息，下次打开时调用方法渲染对应的 range 就行

**Comment by gaoxin3220119** [comment]
也已经搞定了，作者太牛了。下一步准备根据你的demo把跳转搞定。

**Comment by gaoxin3220119** [comment]
也已经搞定了，作者太牛了。



能不能实现根据ID跳转到对应的内容？


我看demo是点击高亮区域的内容后，会高亮评论。我现在的需求是根据id，跳到高亮区域。

**Comment by DLillard0** [comment]
@gaoxin3220119 我在 1.0.6 版本添加了 [getRangePositions](https://github.com/DLillard0/canvas-highlighter/#instance-methods) 实例方法，可以获取高亮区域的位置信息，可以参考这个[代码](https://github.com/DLillard0/canvas-highlighter/blob/main/index.html#L148)实现你的跳转功能

**Comment by gaoxin3220119** [comment]
给力！！！

**Comment by gaoxin3220119** [comment]
我搞了一个 obsidian 的插件： [obsidion-docx-plugin](https://github.com/gaoxin3220119/obsidian-docx-plugin) 用了你的代码，再次谢谢！
